version: '3'
services:
  kafka:
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    image: confluentinc/cp-kafka:6.2.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    image: confluentinc/cp-zookeeper:6.2.0
    ports:
      - "2181:2181"
